version: '3'

networks:
  inception:
    driver: bridge

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
    #! recheck the adress of the volumes
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    env_file:
      - .env 
      # args:
      #   DB_NAME: ${DB_NAME}
      #   DB_USER: ${DB_USER}
      #   DB_PASS: ${DB_PASS}
      #   DB_ROOT: ${DB_ROOT}
    expose:
      - 3306
    volumes:
      - maria_volume:/var/lib/mysql
    networks:
      - inception
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    restart: always
    env_file:
      - .env
    expose:
      - 9000
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception

volumes:
  maria_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/yaidriss42/data/maria-volume
  wordpress_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/yaidriss42/data/wordpress-volume